sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - python3
    - python3-pip
before_install:
  - sudo pip3 install SolrClient
  - docker build -t solr_image .
script:
  - ./test.py
